# ----------------------------
# Configuration File
# ----------------------------

dataset:
  name: "davis"            # options: davis / kiba
  path: "data/processed/davis.pkl"

training:
  epochs: 10
  batch_size: 64
  learning_rate: 0.0001
  split_ratio: 0.83
  device: "cuda"            # or "cpu"
  save_path: "models/deepdta_davis.pth"

model:
  drug_vocab_size: 65
  prot_vocab_size: 25
  drug_max_len: 85
  prot_max_len: 1200
  emb_dim: 128
  num_filters: 32
  fc_dim: 1024
  dropout: 0.1
